require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'


Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']
