version: '3'
services:
  app:
    container_name: insurance-service
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/app
    ports:
      - 3000:3000
    expose:
      - '3000'
    env_file: 
      - .env
    networks:
      - insurance-service
      - db-insurance
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - insurance_service_data:/var/lib/postgresql/data
    networks:
      - db-insurance

volumes:
  insurance_service_data:
networks: 
  insurance-service: 
    external: false
  db-insurance:
    external: false
