default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  user: <%= ENV['POSTGRES_USER'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: insurance_service_development

test:
  <<: *default
  database: insurance_service_test
  host: <%= ENV['POSTGRES_HOST'] || 'postgres' %>
  user: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>

production:
  <<: *default
  database: insurance_service_production
